kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-es-cluster-2
spec:
  storageClassName: k8s-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
