apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-es-cluster-2
  labels:
    type: local
spec:
  storageClassName: k8s-local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:     
    namespace: elastic-logging
    name: data-es-cluster-2
  hostPath:
    path: "/srv/nfs/kubedata"
